### ISSUE TITLE
New sheets of current month cannot be created

### ISSUE THREAD

**Issue by Sebazzz** [Sebazzz/financial-app#64]
Stack trace:

```
Nov 01 16:13:27 fa-app-prod financial-app[58462]: System.InvalidOperationException: The entity of type 'Sheet' is sharing the table 'Sheet' with entities of type 'CalculationOptions', but there is no entity of this type with the same key value that has been marked as 'Added'. Consider using 'DbContextOptionsBuilder.EnableSensitiveDataLogging' to see the key values.
Nov 01 16:13:27 fa-app-prod financial-app[58462]:    at Microsoft.EntityFrameworkCore.Update.Internal.CommandBatchPreparer.Validate(Dictionary`2 sharedTablesCommandsMap)
Nov 01 16:13:27 fa-app-prod financial-app[58462]:    at Microsoft.EntityFrameworkCore.Update.Internal.CommandBatchPreparer.CreateModificationCommands(IReadOnlyList`1 entries, Func`1 generateParameterName)
Nov 01 16:13:27 fa-app-prod financial-app[58462]:    at Microsoft.EntityFrameworkCore.Update.Internal.CommandBatchPreparer.BatchCommands(IReadOnlyList`1 entries)+MoveNext()
Nov 01 16:13:27 fa-app-prod financial-app[58462]:    at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(DbContext _, ValueTuple`2 parameters)
Nov 01 16:13:27 fa-app-prod financial-app[58462]:    at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
Nov 01 16:13:27 fa-app-prod financial-app[58462]:    at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(IEnumerable`1 commandBatches, IRelationalConnection connection)
Nov 01 16:13:27 fa-app-prod financial-app[58462]:    at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IReadOnlyList`1 entriesToSave)
Nov 01 16:13:27 fa-app-prod financial-app[58462]:    at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
Nov 01 16:13:27 fa-app-prod financial-app[58462]:    at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
Nov 01 16:13:27 fa-app-prod financial-app[58462]:    at App.Models.Domain.Services.SheetRetrievalService.GetBySubject(Int32 month, Int32 year, Int32 ownerId) in Z:\Dev\financial-app\src\App\Models\Domain\Services\SheetRetrievalService.cs:line 74
Nov 01 16:13:27 fa-app-prod financial-app[58462]:    at App.Api.SheetController.GetBySubject(Int32 month, Int32 year) in Z:\Dev\financial-app\src\App\Api\SheetController.cs:line 63
Nov 01 16:13:27 fa-app-prod financial-app[58462]:    at lambda_method(Closure , Object , Object[] )
Nov 01 16:13:27 fa-app-prod financial-app[58462]:    at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
Nov 01 16:13:27 fa-app-prod financial-app[58462]:    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
Nov 01 16:13:27 fa-app-prod financial-app[58462]:    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
Nov 01 16:13:27 fa-app-prod financial-app[58462]:    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
Nov 01 16:13:27 fa-app-prod financial-app[58462]:    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
Nov 01 16:13:27 fa-app-prod financial-app[58462]:    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
Nov 01 16:13:27 fa-app-prod financial-app[58462]:    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextExceptionFilterAsync()
Nov 01 16:13:27 fa-app-prod financial-app[58462]:    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ExceptionContext context)
Nov 01 16:13:27 fa-app-prod financial-app[58462]:    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
Nov 01 16:13:27 fa-app-prod financial-app[58462]:    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
Nov 01 16:13:27 fa-app-prod financial-app[58462]:    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
Nov 01 16:13:27 fa-app-prod financial-app[58462]:    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
Nov 01 16:13:27 fa-app-prod financial-app[58462]:    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
Nov 01 16:13:27 fa-app-prod financial-app[58462]:    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
Nov 01 16:13:27 fa-app-prod financial-app[58462]:    at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
Nov 01 16:13:27 fa-app-prod financial-app[58462]:    at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
Nov 01 16:13:27 fa-app-prod financial-app[58462]:    at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
Nov 01 16:13:27 fa-app-prod financial-app[58462]:    at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
Nov 01 16:13:27 fa-app-prod financial-app[58462]:    at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.Invoke(HttpContext context)
Nov 01 16:13:27 fa-app-prod financial-app[58462]:    at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
Nov 01 16:13:27 fa-app-prod financial-app[58462]:    at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.Invoke(HttpContext context)
```

**Comment by Sebazzz** [comment]
Workaround:

``` SQL
INSERT INTO dbo.Sheet (CreateTimestamp, Name, OwnerId, Subject, UpdateTimestamp)
SELECT SYSDATETIME(), NULL, ao.Id, '2018-11-01 00:00:00.0000000', SYSDATETIME()
FROM AppOwner ao
```
